In this notebook, I classify the videos into categories based on their title.

Create the connection to the database.

In [2]:
import sqlite3
import pandas as pd 

conn = sqlite3.connect('../data/lafc_content.db')

Open the stored SQL query with combined video vs lafc match context table, and pull it into the base_df dataframe.

In [3]:
query = '''
SELECT *
FROM videos 
'''
videos_df = pd.read_sql(query, conn)

videos_df

,video_id,channel_id,title,description,published_at,duration,view_count,like_count,comment_count,fetched_at
0,J8KtvKKDsBI,UCnqj91wjXAT0bsmxF1fHWBA,Inside LAFC | Episode 211 - A Strong Start,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-21T08:27:48Z,PT49M46S,1129,88,4,2026-07-21T18:13:52.868219+00:00
1,6IGiJLX6zIA,UCnqj91wjXAT0bsmxF1fHWBA,Sonny's goal from pitchside 🤳,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-21T05:15:15Z,PT17S,9169,901,20,2026-07-21T18:13:52.868219+00:00
2,dk5FTY2zHEI,UCnqj91wjXAT0bsmxF1fHWBA,Son Heung-Min | EVERY ANGLE of his derby goal ...,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-20T07:17:45Z,PT2M10S,10782,1373,100,2026-07-21T18:13:52.868219+00:00
3,WGLkpecuCyA,UCnqj91wjXAT0bsmxF1fHWBA,LAFC Weekly | Episode 15 | 2026,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-19T01:00:21Z,PT21M,2106,167,9,2026-07-21T18:13:52.868219+00:00
4,rjdbdSE3TNo,UCnqj91wjXAT0bsmxF1fHWBA,A Night To Remember | LAG vs LAFC,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-18T22:58:28Z,PT25S,2759,457,31,2026-07-21T18:13:52.868219+00:00
...,...,...,...,...,...,...,...,...,...,...
3566,8yoRN5MvJP0,UCnqj91wjXAT0bsmxF1fHWBA,Somos LAFC,"Nuestra Ciudad, Nuestro Club, Nuestro Escudo. ...",2016-01-08T00:27:56Z,PT2M,10264,165,16,2026-07-21T18:13:52.868219+00:00
3567,Emczin-vSFQ,UCnqj91wjXAT0bsmxF1fHWBA,WE ARE LAFC,"Our City, Our Club, Our Crest. We are LAFC.",2016-01-07T17:51:44Z,PT2M,146275,1160,191,2026-07-21T18:13:52.868219+00:00
3568,a63ytKgBTAc,UCnqj91wjXAT0bsmxF1fHWBA,John Thorrington announcement on SportsCenter,"Check out SportsCenter, giving some airtime to...",2015-12-09T23:54:13Z,PT27S,2094,24,2,2026-07-21T18:13:52.868219+00:00
3569,QJP0ITdmAeo,UCnqj91wjXAT0bsmxF1fHWBA,Building Together: LAFC Stadium Workshop,We asked our supporters to help us design our ...,2015-11-24T19:50:33Z,PT1M1S,6295,73,5,2026-07-21T18:13:52.868219+00:00
3570,BPO8RNyuCHs,UCnqj91wjXAT0bsmxF1fHWBA,A Look Back at Year One,Today we proudly mark the one-year anniversary...,2015-10-30T17:09:11Z,PT1M,5611,81,7,2026-07-21T18:13:52.868219+00:00

Import Tfid and kMeans from scikit learn.

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

Create a series of titles from the base data frame, I'm ignoring the description because it's repeated across different types of videos, and biases clustering.

In [4]:
text = videos_df['title'].fillna('')
text.head()

0           Inside LAFC | Episode 211 - A Strong Start
1                        Sonny's goal from pitchside 🤳
2    Son Heung-Min | EVERY ANGLE of his derby goal ...
3                      LAFC Weekly | Episode 15 | 2026
4                    A Night To Remember | LAG vs LAFC
Name: title, dtype: str

Adding (too) commonly occuring title words to the English stop words list:

In [5]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
custom = ENGLISH_STOP_WORDS.union({'lafc','https','com','www','la','los','angeles','ep','episode'})

Vectorize the text series, into a sparse matrix, using tfid, and load it in a feature variable X.

In [6]:
vec = TfidfVectorizer(
    stop_words=list(custom),   # use my custom words as stop_words
    ngram_range=(1, 2),     # single words AND 2-word phrases ("inside lafc")
    min_df=5,               # ignore terms that appear in fewer than 5 videos (rare noise)
    max_df=0.4,
    max_features=500,       # cap vocabulary size — keeps it fast/focused
)
X = vec.fit_transform(text)

Create the kmeans model and assign each video a cluster.

In [7]:
k = 8
km = KMeans(n_clusters=k, random_state=11, n_init=10)
videos_df['cluster'] = km.fit_predict(X)

Examining the clusters:

In [8]:
terms = vec.get_feature_names_out()
for c in range(k):
    top_idx = km.cluster_centers_[c].argsort()[-10:][::-1]   # 10 highest-weight terms
    keywords = ", ".join(terms[i] for i in top_idx)
    examples = videos_df[videos_df.cluster == c]['title'].head(3).tolist()
    print(f"\ncluster {c} (n={(videos_df.cluster==c).sum()})")
    print(f"  keywords: {keywords}")
    print(f"  examples: {examples}")

cluster 0 (n=2193)
  keywords: mls, weekly, football, bouanga, vs, crest, banc, armando, acción armando, acción
  examples: ['LAFC Weekly | Episode 15 | 2026', 'A Night To Remember | LAG vs LAFC', 'Sonny back on the scoresheet 🫡']

cluster 1 (n=126)
  keywords: media, vs, prematch media, prematch, postmatch media, postmatch, vs prematch, vs postmatch, col, atx
  examples: ['LAG vs LAFC | Postmatch Media', 'LAG vs LAFC | Prematch Media', 'LAFC vs SEA | Postmatch Media']

cluster 2 (n=82)
  keywords: mvp podcast, mvp, podcast, special, special guest, guest, cup, ilie, john, jordan harvey
  examples: ['MVP Podcast Ep. 77 - Time To Regroup with special guest Denil Maldonado', 'MVP Podcast Ep. 76 - Road Work with Special Guest Daniel Crisostomo', 'MVP Podcast Ep. 75 - Changing The Batteries with Special Guest Julian Gaines']

cluster 3 (n=163)
  keywords: inside, inside podcast, podcast, max vince, vince, max, inside max, cup, john, home
  examples: ['Inside LAFC | Episode 211 - A Strong Start', 'Inside LAFC | Episode 210 - MLS Is Back', 'Inside LAFC | Episode 209 - World Cup Preview']

cluster 4 (n=214)
  keywords: gold, black gold, black, gold insider, insider, gold weekly, weekly, presented, goal, ryan
  examples: ['LA is Black & Gold.', 'Black & Gold Insider Ep. 55 | Yevhen Cheberko', 'Yevhen Cheberko is Black & Gold']

cluster 5 (n=357)
  keywords: goal, cherundolo, vs, steve cherundolo, steve, touch steve, touch, bouanga, mls goal, bouanga vs
  examples: ["Sonny's goal from pitchside 🤳", 'Son Heung-Min | EVERY ANGLE of his derby goal | LAG vs LAFC', 'SONNY’S FIRST GOAL OF THE SEASON | LAG vs LAFC']

cluster 6 (n=306)
  keywords: highlights, vs, highlights vs, fc, recap vs, recap, 21, 23, 2018, galaxy
  examples: ["Galaxy vs. LAFC | MATCH HIGHLIGHTS | SONNY'S FIRST OF THE SEASON", 'LAFC vs. Seattle Sounders | MATCH HIGHLIGHTS | Tillman late goal', 'San Diego FC vs. LAFC | MATCH HIGHLIGHTS']

cluster 7 (n=130)
  keywords: vela, carlos, carlos vela, goal carlos, goal, goals, mls, galaxy, scores, vs
  examples: ["EVERY Goal from Carlos Vela's Golden Boot Season | MLS 2019 | Historic 34 Goal Season!", 'Carlos Vela | Captain. Champion. Owner', 'Inside LAFC | Episode 174 - Noche de Carlos Vela']

Based on the clustered keywords, I created a rules based classify function. I also created a format family dictionary, to group related cateogries, post function.

In [4]:
def classify_format(title):
    """
    Rule-based format classifier for LAFC videos.
    Order matters: named series first, then press/interview, then match content,
    then themed content, catch-all last. First match wins. Title-only, no regex.
    """
    t = str(title).lower()

    # 1. Named recurring series
    if 'inside lafc' in t:                                          return 'inside_lafc'
    if 'gold insider' in t:                                         return 'black_and_gold'   # the SHOW only
    if 'is black & gold' in t or 'is black and gold' in t:          return 'signing'          # "X is Black & Gold"
    if 'mvp podcast' in t:                                          return 'mvp_podcast'
    if 'acción' in t or 'accion' in t:                             return 'accion_lafc'
    if 'lafc weekly' in t or 'weekly | ' in t:                     return 'lafc_weekly'
    if 'lafc+' in t or 'lafc +' in t:                              return 'lafc_plus'
    if 'on the mic' in t:                                           return 'on_the_mic'
    if 'behind the crest' in t:                                     return 'behind_the_crest'
    if 'away days' in t:                                            return 'away_days'
    if 'a lot more to prove' in t:                                  return 'more_to_prove'
    if 'staying home' in t:                                         return 'staying_home'
    if '안녕 lafc' in t:                                            return 'korean_series'
    if 'podcast' in t:                                              return 'other_podcast'

    # 2. Press / interview (keyword-based)
    if 'postmatch' in t or 'post-match' in t:                      return 'postmatch_media'
    if 'prematch' in t or 'pre-match' in t:                        return 'prematch_media'
    if 'conference' in t or 'presser' in t or 'media availab' in t:  # 'availab' catches the typo
        return 'presser'
    if any(w in t for w in ['in touch','speaks','discusses','talks ',
                            'thoughts','reacts','reaction','breaks down','sits down']):
        return 'interview'

    # 3. Match content
    if 'highlight' in t or 'all goals' in t or 'every goal' in t or 'goal scored' in t \
       or 'top ten goals' in t or 'top 10 goals' in t or 'best goals' in t or 'top goals' in t:
        return 'highlights'
    if ('goal:' in t or t.startswith('goal ') or t.startswith('goal!')
            or '| goal' in t or 'every angle' in t or 'wondergoal' in t or 'golazo' in t
            or 'game winner' in t or 'from the spot' in t or 'from pitchside' in t):
        return 'goal_clip'
    if 'save of the match' in t or 'huge save' in t or 'leaping save' in t or 'big save' in t:
        return 'save_clip'
    if 'match frames' in t:                                         return 'match_frames'
    if 'preview' in t or 'keys to the match' in t:                 return 'match_preview'
    if 'recap' in t:                                                return 'recap'

    # 4. Themed / behind-the-scenes / features
    if 'behind the scenes' in t or 'sounds of' in t:               return 'behind_the_scenes'
    if 'training' in t or "mic'd up" in t or 'micd up' in t:       return 'training'
    if 'watch party' in t or 'watch along' in t or 'watch-along' in t or '110 football' in t:
        return 'watch_party'
    if 'built for it' in t:                                         return 'built_for_it'
    if any(w in t for w in ['get to know','player profile','lafc profile','join the club',
                            'on this day','cali to cali']):         return 'feature'

    # 5. Catch-all
    return 'unclassified'


FORMAT_FAMILY = {
    # produced recurring series
    'inside_lafc':      'show',
    'black_and_gold':   'show',
    'mvp_podcast':      'show',
    'accion_lafc':      'show',
    'lafc_weekly':      'show',
    'lafc_plus':        'show',
    'on_the_mic':       'show',
    'behind_the_crest': 'show',
    'away_days':        'show',
    'more_to_prove':    'show',
    'staying_home':     'show',
    'korean_series':    'show',
    'other_podcast':    'show',

    # match content
    'highlights':       'match',
    'goal_clip':        'match',
    'save_clip':        'match',
    'match_frames':     'match',
    'match_preview':    'match',
    'recap':            'match',

    # press / interview
    'postmatch_media':  'media',
    'prematch_media':   'media',
    'presser':          'media',
    'interview':        'media',

    # themed / features
    'behind_the_scenes':'behind_scenes',
    'training':         'behind_scenes',
    'watch_party':      'watch_party',
    'built_for_it':     'feature',
    'feature':          'feature',
    'signing':          'signing',

    # catch-all
    'unclassified':     'unclassified', 
}

Apply the classify function, and map the format family, to two new columns in the base_df, then count them:

In [5]:
videos_df['content_type']   = videos_df['title'].apply(classify_format)
videos_df['format_family']  = videos_df['content_type'].map(FORMAT_FAMILY)

videos_df['content_type'].value_counts()

content_type
unclassified         1903
highlights            247
goal_clip             169
inside_lafc           164
lafc_weekly           111
lafc_plus             103
accion_lafc            86
mvp_podcast            82
recap                  65
match_preview          64
signing                63
prematch_media         61
postmatch_media        57
black_and_gold         55
interview              55
behind_the_crest       49
feature                47
presser                40
watch_party            40
training               36
behind_the_scenes      21
korean_series          12
match_frames           11
away_days               9
on_the_mic              8
save_clip               4
other_podcast           3
staying_home            3
built_for_it            2
more_to_prove           1
Name: count, dtype: int64

Even with all my rules, many of the videos are not easily classifiable by title, those are assigned the category of "unclassified".

In [11]:
videos_df[['title', 'format_family']].sample(30)

                                                  title format_family
852                                  Xolo vibe check ✔️  unclassified
1772                                     LAFC+ | Ep. 14          show
2693  LAFC Profile | Canada Connection Dejan Jakovic...       feature
129           Inside LAFC | Episode 203 - Looking ahead          show
3250             GOAL Walker Zimmerman | LAFC 1 - 0 COL         match
51                        LAFC vs SEA | Postmatch Media         media
1445  First goal in Black & Gold for Lewis O'Brien |...  unclassified
126             Acción LAFC Con Armando Aguayo | Ep. 84          show
1874      Part of our History | Diego "Chiqui" Palacios  unclassified
1736            LAFC Weekly Presented by Carmax - Ep. 9          show
1888    Highlights | LAFC vs. Seattle Sounders 11/26/23         match
1800                                     LAFC+ | Ep. 10          show
2398                  110 FOOTBALL x LAFC | Galaxy Week   watch_party
385             Acción LAFC Con Armando Aguayo | Ep. 78          show
472                                BOUANGA, FAR POST ⚡️  unclassified
1720                Behind the Crest | Veteran Presence          show
2912                GOAL!!! Lee Nguyen | RSL 0 - 2 LAFC         match
3076  EPIC WINNER: Adama Diomande Scores in 94th Min...  unclassified
1944      Black & Gold Weekly | LAFC vs. Inter Miami CF          show
1156  LAFC2 Report | Recapping The Season And Lookin...         match
47      On This Day | LAFC vs Club América | 05.31.2025       feature
1033                                     LAFC+ | Ep. 46          show
1670                    Off the Pitch with Nathan Ordaz  unclassified
217                 Mathieu's night at BMO Stadium ⚽️⚽️  unclassified
2699  LAFC Goal Rush Inaugural Season | Top 5 Goals ...  unclassified
759                        LAFC vs FLA | Prematch Media         media
2459                        LAFC's Top 10 Goals Of 2020         match
3435  Relive LAFC's Home-Opener at Banc of Californi...  unclassified
518                 Sonny wasting no time in San Jose 🤩  unclassified
1061               Hollingshead. Back Post. Five-Hole 💥  unclassified

I tuned the classification based on rules as best I could, but I still had ≈ 1800 videos that I was labeling "unclassified" they were mostly short social clips without a standard title, but some were interview clips, so I decided to try a light machine learning model on the "unclassified" set to see if I could label those more finely.

In [6]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')

/Users/laptop_02/Documents/data_projects/lafc_content/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
'[Errno 8] nodename nor servname provided, or not known' thrown while requesting HEAD https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/adapter_config.json
Retrying in 1s [Retry 1/5].

RuntimeError: Cannot send a request, as the client has been closed.

In [13]:
CATEGORIES = {
    'goal_clip':   'a video clip of a single goal being scored in a match',
    'highlights':  'match highlights or a compilation of multiple goals',
    'interview':   'a player or coach speaking, quote, press interview or reaction',
    'feature':     'a player profile, personal story, or getting-to-know feature',
    'behind_the_scenes': 'behind the scenes footage, training, or documentary content',
    'match_preview':'a preview or build-up before an upcoming match',
    'recap':       'a season or match recap looking back',
    'misc_social_clip': 'a short hype or social media clip, slogan, or promotional post',
}

In [14]:
cat_names = list(CATEGORIES.keys())
cat_embeddings = model.encode(list(CATEGORIES.values()))

In [15]:
unclassified = videos_df[videos_df['content_type'] == 'unclassified'].copy()
title_embeddings = model.encode(unclassified['title'].fillna('').tolist(), show_progress_bar=True)

Batches: 100%|██████████| 60/60 [00:01<00:00, 32.20it/s]

In [16]:
import numpy as np
sims = util.cos_sim(title_embeddings, cat_embeddings).numpy()   # shape: (n_titles, n_categories)
best_idx   = sims.argmax(axis=1)     # which category scored highest per title
best_score = sims.max(axis=1)        # how strong that match was
unclassified['ml_label'] = [cat_names[i] for i in best_idx]
unclassified['ml_score'] = best_score

In [17]:
THRESHOLD = 0.30   # tune this — see below
unclassified['ml_label'] = np.where(
    unclassified['ml_score'] >= THRESHOLD,
    unclassified['ml_label'],
    'misc_social_clip'          # weak match -> genuine miscellany
)

In [18]:
unclassified[['title', 'ml_label', 'ml_score']].sample(30)

,title,ml_label,ml_score
3113,Zimmerman and Ramirez Return From USMNT Camp,misc_social_clip,0.241218
3254,Anatomy Of A Goal | Diego Rossi vs Chicago Fir...,goal_clip,0.512476
895,Nathan Ordaz goal vs HOU,highlights,0.323035
2467,What It Will Take To Conquer The CONCACAF Cham...,misc_social_clip,0.214680
2648,LAFC Welcomes New 2020 Members At Banc Of Cali...,misc_social_clip,0.109377
459,New friends 🤝,misc_social_clip,0.190019
788,Bouanga Magic 🪄,misc_social_clip,0.084287
1302,"Cherundolo: We're Ready, Have Some Ideas In Pl...",misc_social_clip,0.158120
2546,LAFC x Farmer John LA | Bresee Foundation #LAF...,misc_social_clip,0.147108
504,SJ vs LAFC | Every Assist,misc_social_clip,0.264993
1187,Lloris: We Need To Do Everything Possible To A...,highlights,0.361038
1057,LAFC vs CLB | Pre match media,match_preview,0.389222
465,Every emotion of Sonny's goal vs RSL,recap,0.327071
629,La Joya 💎,misc_social_clip,0.182986
1199,"Bouanga: We're Going To Have To Be Offensive, ...",highlights,0.356747
2745,LAFC x Porsche | A Look Inside Lee Nguyen's Pr...,misc_social_clip,0.232996
1818,Faces of LAFC: Black and Gold Running Club,misc_social_clip,0.262402
98,Hugo Lloris with the double save,misc_social_clip,0.298776
2986,Steven Beitashour With Sam & Nat On KTLA 5 Live,misc_social_clip,0.278813
3199,Carlos Vela Reflects On Inaugural Season,misc_social_clip,0.267778
1498,😉,misc_social_clip,0.097569
3319,US Open Cup | Plenty To Build On,misc_social_clip,0.269780
677,DILROSUN DELIVERS!,misc_social_clip,0.111952
3513,LAFC Youth Leadership Program,misc_social_clip,0.179853
1425,From the Pitch: Kamara On LAFC's Open Cup Semi...,recap,0.405048
3055,Steven Beitashour Surprises LAFC Family With B...,misc_social_clip,0.286311
1984,LAFC Academy Report | Homegrown Talent,interview,0.306423
1273,Entering a new era of fast 💨 | #Adidas #Adidas...,misc_social_clip,0.266681
1373,Bouanga: We Need To Be More Combative and Dete...,misc_social_clip,0.213413
1027,Back Home 🏡,misc_social_clip,0.215935

In [19]:
unclassified['ml_score'].describe()

count    1903.000000
mean        0.248524
std         0.093207
min         0.024242
25%         0.182518
50%         0.244476
75%         0.307881
max         0.584862
Name: ml_score, dtype: float64

In [20]:
unclassified['dur_min'] = pd.to_timedelta(unclassified['duration']).dt.total_seconds() / 60

u = unclassified.sort_values('ml_score', ascending=False)

print("=== HIGH scores (top matches) ===")
print(u.head(15)[['title','ml_label','ml_score','dur_min']].round({'ml_score':3,'dur_min':1}).to_string())

print("\n=== MID scores (around the median) ===")
print(u.iloc[900:915][['title','ml_label','ml_score','dur_min']].round({'ml_score':3,'dur_min':1}).to_string())

print("\n=== LOW scores (weakest) ===")
print(u.tail(15)[['title','ml_label','ml_score','dur_min']].round({'ml_score':3,'dur_min':1}).to_string())

=== HIGH scores (top matches) ===
                                                                         title    ml_label  ml_score  dur_min
3479                    WATCH: A closer look at the first goal in LAFC history   goal_clip     0.585      0.5
405                                             ✌️ Regular season matches left       recap     0.570      0.3
714                                    Goals in back-to-back matches for Ordaz  highlights     0.527      0.5
853                                                     4️⃣ goals in one place  highlights     0.526      0.6
2882                       11 Goals Over In Our Last 2 Games | Watch Them All!  highlights     0.524      1.0
1446                    1 Goal = 3 Celebrations | #LAFC #MLS #LeaguesCup #Goal  highlights     0.518      0.2
2917                Anatomy Of A Goal | Diego Rossi vs Portland Timbers 6/1/19   goal_clip     0.517      2.4
3106                                            The Can't Miss Matches Of 2019       recap     0.515      5.8
3254                      Anatomy Of A Goal | Diego Rossi vs Chicago Fire 9/29   goal_clip     0.512      2.2
2896                LAFC Coaches On The Significance Of National Team Call-Ups   interview     0.507      1.0
653                                                         One goal in mind 🏆  highlights     0.507      0.4
2790  Anatomy Of A Goal | Carlos Vela's "Houdini" Goal vs San Jose Earthquakes   goal_clip     0.503      4.0
3221              Anatomy Of A Goal | Diego Rossi vs Vancouver Whitecaps 10/21   goal_clip     0.502      2.3
3481                        Diego Rossi Scores The First Goal in LAFC History!   goal_clip     0.499      1.2
3298                  Carlos Vela Goal vs. Galaxy | Slow Motion | Penalty Kick   goal_clip     0.495      0.6

=== MID scores (around the median) ===
                                                                                       title          ml_label  ml_score  dur_min
1774                                                            Can't catch Denis Bouanga ✌️  misc_social_clip     0.251      0.2
3529                                        Bob Bradley on Counter Attack with Brian Dunseth  misc_social_clip     0.250     10.4
1447                                        Another Bogusz Banger | #LAFC #MLS #Goal #Bogusz  misc_social_clip     0.250      0.2
1377                                         Back together 🫂  | #LAFC #MLS #Vela #CarlosVela  misc_social_clip     0.250      0.6
748                                                                "It's yours, my friend" 🏆  misc_social_clip     0.250      0.5
2579                                  Shootin' The Shot With Larry & Harv Ep 4 | Jaime Camil  misc_social_clip     0.250     55.7
2994                                                   2019 Forwards | A Free Flowing Attack  misc_social_clip     0.250      2.7
2665                                            Bob Bradley On Francisco Ginella's Potential  misc_social_clip     0.250      1.6
2911                                   Rodolfo Fito Zelaya Free Kick ROCKET | RSL 0 - 3 LAFC  misc_social_clip     0.249      1.0
3030                  Los Angeles Lakers Guard, NCAA Champion Josh Hart Sings with LAFC Fans  misc_social_clip     0.249      1.0
2495                                  LAFC Fan Profile | #AlwaysTogether With Gerry Sadowski  misc_social_clip     0.249      1.8
1355                   LAFC Supporters League Mid-Season Invitational | Powered by McDonalds  misc_social_clip     0.249    101.3
3338                                                   The Blackout Starts Now | #BlackoutLA  misc_social_clip     0.249      0.5
1361  Hollingshead: Big Game In Dallas, Gotta Get Points And Get Back To The Top Of The West  misc_social_clip     0.249      5.3
2375                   Security Supervisor & More | Players Show Their Love For Paul Apodaca  misc_social_clip     0.249      1.8

=== LOW scores (weakest) ===
                                                                                      title          ml_label  ml_score  dur_min
1109                                                                              24 Hours⏳  misc_social_clip     0.052      0.3
2470                       LAFC & Target Donate Thanksgiving Meal Boxes To Families In Need  misc_social_clip     0.052      1.5
945                                                              Un recuerdo espectacular 🤩  misc_social_clip     0.051      0.4
883                                                                              24 Hours ⏳  misc_social_clip     0.049      1.0
900                                                                              24 Hours ⏳  misc_social_clip     0.049      1.0
954                                                                              24 Hours ⏳  misc_social_clip     0.049      0.8
1056                                                                             24 Hours ⏳  misc_social_clip     0.049      0.8
3239                                        Anatomy Of A Brace | Adama Diomande at Colorado  misc_social_clip     0.045      1.9
2538  Eduard Atuesta | Justice For Vanessa Guillén & The Indigenous Population Of Colombia.  misc_social_clip     0.039      1.5
3105                                              The 3252 Hold Elections For Key Positions  misc_social_clip     0.037      1.4
2448                                                           Join The Black & Gold Family  misc_social_clip     0.037      2.0
3054                                         LAFC Honored By LA County Board Of Supervisors  misc_social_clip     0.035      1.4
254                                                                       99 is electric ⚡️  misc_social_clip     0.033      0.2
2507                                     LAFC Provides Over 500 Families With Fresh Produce  misc_social_clip     0.027      1.9
1628                 Cherundolo: This Is A Very Healthy Group; They Take Care Of Each Other  misc_social_clip     0.024      4.7

The light ml model did well at recognizing goal and highlight clips, but it was missing interview clips. I decide to provide the model with category vectors based on actual examples titles for each category, instead of providing it with text descriptions of the categories, to see if that would improve its classification.

In [21]:
PROTOTYPES = {
    'goal_clip': [
        # structured (with score line)
        "GOAL: M. Bogusz vs VAN, 1'",
        "Denis Bouanga breaks the tie! LAFC 2 - 1 HOU",
        "Diego Rossi opens the scoring, LAFC 1 - 0 Dallas",
        # short descriptive goal moments (no score line — the leaking shape)
        "Sonny picks his spot 🎯",
        "Near post finish by Bouanga 😮‍💨",
        "Bouanga chips the keeper | ALL ANGLES",
        "SONNY FROM DISTANCE 🚀",
        "Timmy's strike from the top of the box",
    ],

    'highlights': [
        "Highlights | LAFC vs FC Dallas",
        "Full Highlights | 3-0 | LAFC vs. Colorado Rapids",
        "MATCH HIGHLIGHTS | LAFC vs Seattle Sounders",
        "Every Goal From LAFC's Inaugural MLS Season",
        "11 Goals Over In Our Last 2 Games | Watch Them All",
    ],
    'interview': [
        "Cherundolo: We'll Need Effort Again Against Austin",
        "Ebobisse: Feeling more and more confident by the day",
        "Bradley Addresses Media After Mark-Anthony Kaye Trade",
        "Bouanga speaks on his hat trick",
        "Nguyen: This Is Where You Start To Play For Playoff Positions",
        "State Of The Union | Tom Penn",
        "Hollingshead: Huge Result For Us, Three Points On The Road",
    ],
    'feature': [
        "Get To Know Kwadwo Opoku",
        "LAFC Profile | From Norway to LA, Adama Diomande",
        "Building A Legacy | Carlos Vela's Past & Future With LAFC",
        "Join The Club | Juan Pinto",
        "The Call-Up | Christian Ramirez",
    ],
    'behind_the_scenes': [
        "Behind The Scenes | 2026 Primary Kit Shoot",
        "Sounds of Training | First Week Back",
        "A Look Behind The Scenes With Equipment Manager Scott Tranilla",
        "Inside the locker room after the win",
    ],
    'match_preview': [
        "LAFC at LA Galaxy - Match Preview",
        "Keys To The Match | LAFC vs Seattle",
        "Previewing the road trip to Colorado",
        "What to watch for ahead of LAFC vs Austin FC",
    ],
    'recap': [
        "2023 LAFC Season Recap",
        "Recap | LAFC vs Colorado Rapids",
        "Looking Back At The 2022 MLS Cup Run",
        "Year In Review | 2021 Season",
    ],
    'misc_social_clip': [
        "24 Hours ⏳",
        "The dagger 🗡️",
        "99 is electric ⚡️",
        "Ready to fight for the Club 🫡",
        "Pressure is a privilege",
        "It's about the collective.",
    ],
}

In [22]:
import numpy as np

cat_names = list(PROTOTYPES.keys())
cat_vectors = []
for name in cat_names:
    ex_embs = model.encode(PROTOTYPES[name])   # embed that category's example titles
    cat_vectors.append(ex_embs.mean(axis=0))   # average -> one "centroid" per category
cat_vectors = np.vstack(cat_vectors)

In [23]:
from sentence_transformers import util

sims = util.cos_sim(title_embeddings, cat_vectors).numpy()
best_idx = sims.argmax(axis=1)
unclassified['ml_label'] = [cat_names[i] for i in best_idx]
unclassified['ml_score'] = sims.max(axis=1)

In [24]:
THRESHOLD = 0.47   # tuned based on running the model a few times at looking at resulting ml scores against titles
unclassified['ml_label'] = np.where(
    unclassified['ml_score'] >= THRESHOLD,
    unclassified['ml_label'],
    'misc_social_clip'
)

In [25]:
unclassified[['title', 'ml_label', 'ml_score']].sample(30)

,title,ml_label,ml_score
1760,Cherundolo: The Performance Was Professional A...,misc_social_clip,0.347951
1398,Segura: Segura: Nos Llevamos Un Punto Bastante...,misc_social_clip,0.269492
1546,Cherundolo: We Saw Opportunities In Transition...,interview,0.497006
606,Son Heung-Min Makes His LAFC Debut.,misc_social_clip,0.455461
788,Bouanga Magic 🪄,goal_clip,0.485454
2658,El Capitán | What Motivates Carlos Vela,feature,0.479225
848,"No boot, no problem 🤷‍♂️",misc_social_clip,0.162450
2467,What It Will Take To Conquer The CONCACAF Cham...,misc_social_clip,0.389635
526,"Good morning, LA 🤩",misc_social_clip,0.380172
2745,LAFC x Porsche | A Look Inside Lee Nguyen's Pr...,misc_social_clip,0.424011
895,Nathan Ordaz goal vs HOU,goal_clip,0.525557
1484,Sánchez: It's All About The Players And The Co...,misc_social_clip,0.405109
2603,From The Stands | LAFC vs. Philadelphia Union,highlights,0.641105
2661,State Of The Union | Bob Bradley,misc_social_clip,0.409718
1865,Team Bonding🏌️‍♂️,misc_social_clip,0.520078
18,Llego el Barrio Angelino 🥁,misc_social_clip,0.455929
360,SONNY SCORES IN THE PLAYOFFS,goal_clip,0.531174
359,DENIS BOUANGA GETS GOAL 100,goal_clip,0.641144
3212,#LAFCTakingOff With Christian Ramirez Presente...,feature,0.549305
2806,A Club For Everybody.,misc_social_clip,0.447964
3239,Anatomy Of A Brace | Adama Diomande at Colorado,misc_social_clip,0.167546
910,Bouanga Blast!,misc_social_clip,0.466825
988,What a strike from Artem Smoliakov 🚀,misc_social_clip,0.363181
2399,"The Past, Present, & Future Of El Clásico Ange...",misc_social_clip,0.331956
2966,Linkin Park Bassist Phoenix Farrell Loves LAFC...,misc_social_clip,0.354164
2883,The Next Chapter | LAFC vs Portland Timbers,recap,0.655723
912,BOUANGA IN THE FINAL MOMENTS 💥,goal_clip,0.636815
3227,Comedian Maz Jobrani Visits The North End,misc_social_clip,0.237288
722,Good luck charm and proud brother 🍀,misc_social_clip,0.312971
3036,"Bradley & Blessing: 'It’s Payback Time, We’re ...",misc_social_clip,0.392144

In [26]:
unclassified['ml_score'].describe()

count    1903.000000
mean        0.442647
std         0.110776
min         0.122112
25%         0.366663
50%         0.443994
75%         0.514534
max         0.823427
Name: ml_score, dtype: float64

In [27]:
unclassified['dur_min'] = pd.to_timedelta(unclassified['duration']).dt.total_seconds() / 60

u = unclassified.sort_values('ml_score', ascending=False)

print("=== HIGH scores (top matches) ===")
print(u.head(15)[['title','ml_label','ml_score','dur_min']].round({'ml_score':3,'dur_min':1}).to_string())

print("\n=== MID scores (around the median) ===")
print(u.iloc[900:915][['title','ml_label','ml_score','dur_min']].round({'ml_score':3,'dur_min':1}).to_string())

print("\n=== LOW scores (weakest) ===")
print(u.tail(15)[['title','ml_label','ml_score','dur_min']].round({'ml_score':3,'dur_min':1}).to_string())

=== HIGH scores (top matches) ===
                                                                                       title       ml_label  ml_score  dur_min
310                                                    A Year In Review | LAFC's 2025 Season          recap     0.823      4.6
3152                                             MEMORABLE MATCHDAY | LAFC Makes MLS History     highlights     0.768      3.9
2594                                               LAFC In 30 | LAFC vs. FC Dallas - 5/19/19     highlights     0.737     30.0
3454                                     WATCH: All 3 Goals in LAFC's 3-4 Loss vs. LA Galaxy     highlights     0.736      2.2
3442                                 WHAT A MATCH: LAFC vs. Montreal Impact | April 21, 2018     highlights     0.735      4.0
3479                                  WATCH: A closer look at the first goal in LAFC history     highlights     0.733      0.5
1716                                                       2024 Preseason: LAFC vs St. Louis          recap     0.725    108.9
3327  Epic Comebacks, Wild Games, Unforgettable Goals | TOP 5 MOMENTS in LAFC's First Season     highlights     0.724      5.2
3336                                         WATCH LAFC vs. Galaxy | 7/26 at 7:30 PM on ESPN  match_preview     0.722      2.1
2844                               LAFC Scores 4 Goals In 12 Minutes Against Atlanta United!     highlights     0.722      1.0
2550                                                    LAFC vs. Houston | Relive The Return  match_preview     0.719      2.9
3118                                                   LAFC Goals vs. Columbus Crew | 2/4/19     highlights     0.717      0.4
2568                                              LAFC In 30 | LAFC vs. Toronto FC - 9/21/19     highlights     0.715     30.0
2591                                         LAFC In 30 | LAFC vs. Montreal Impact - 5/24/19     highlights     0.709     29.4
2572                                             LAFC In 30 | LAFC vs. Orlando City - 9/7/19  match_preview     0.703     30.0

=== MID scores (around the median) ===
                                                            title          ml_label  ml_score  dur_min
584                                                     Tonight ⏳  misc_social_clip      0.45      0.9
55                                                      Tonight ⏳  misc_social_clip      0.45      0.8
685                                                     Tonight ⏳  misc_social_clip      0.45      0.7
745                                                     Tonight ⏳  misc_social_clip      0.45      0.4
68                                                      Tonight ⏳  misc_social_clip      0.45      0.3
657                                                     Tonight ⏳  misc_social_clip      0.45      0.9
121                                                     Tonight ⏳  misc_social_clip      0.45      0.5
757                                                     Tonight ⏳  misc_social_clip      0.45      0.4
20                                                      Tonight ⏳  misc_social_clip      0.45      0.8
561                                                     Tonight ⏳  misc_social_clip      0.45      0.8
641                                                     Tonight ⏳  misc_social_clip      0.45      0.4
1184  Come for the goal. Stay for the celebration🏌️‍♂️| #playoffs  misc_social_clip      0.45      0.3
2964                          Best Moments | One Year At The Banc  misc_social_clip      0.45      1.9
816                           Forever a legend, thank you Carlos.  misc_social_clip      0.45      3.2
818   Mark Delgado is there to meet the cross from Nathan Ordaz 👊  misc_social_clip      0.45      0.2

=== LOW scores (weakest) ===
                                                                  title          ml_label  ml_score  dur_min
2389            Know Before You Go | Vaccinated-Only Sections Explained  misc_social_clip     0.190      3.0
3166                                Will Ferrell On The Rich Eisen Show  misc_social_clip     0.185      0.4
3500          Owner Tony Robbins Visits Banc Of California Stadium Site  misc_social_clip     0.177      1.0
2130  Kellyn Acosta Serves As Nisei Week Parade Honorary Grand Marshall  misc_social_clip     0.174      0.9
3239                    Anatomy Of A Brace | Adama Diomande at Colorado  misc_social_clip     0.168      1.9
1878                         Giorgio Chiellini Announces His Retirement  misc_social_clip     0.166      2.3
3162       Tastemakers Ep. 2 | Mark-Anthony Kaye makes Rabbit Agnolotti  misc_social_clip     0.165     12.8
2936                  WNBA Champion Nneka Ogwumike Experiences The 3252  misc_social_clip     0.163      1.0
848                                            No boot, no problem 🤷‍♂️  misc_social_clip     0.162      0.7
3037                 Superfan "The Scarf" Designs Special Edition Scarf  misc_social_clip     0.160      6.2
2876                         How Cancer Has Changed Tyler Miller's Life  misc_social_clip     0.149      2.8
1952                           A Mother's Love | Timothy & Anja Tillman  misc_social_clip     0.145      4.2
3105                          The 3252 Hold Elections For Key Positions  misc_social_clip     0.142      1.4
2447                                  Black History Is American History  misc_social_clip     0.128      1.4
945                                          Un recuerdo espectacular 🤩  misc_social_clip     0.122      0.4

It did a better job at classifying, and I went back and adjusted the ml_score threshold (below that the model would default a row to misc_social_clip). Then I merged the data frame of previously unclassified, back into the base_df, adding a content_type_final_column.

In [1]:
import numpy as np

# 1. Apply the threshold -> final label for the unclassified rows
THRESHOLD = 0.47
unclassified['final_label'] = np.where(
    unclassified['ml_score'] >= THRESHOLD,
    unclassified['ml_label'],
    'misc_social_clip'
)

# FORMAT_FAMILY was written before the ML pass existed, so it has no entry
# for the one category only the model can produce. Add it here rather than
# editing the original dict, to keep the order of discovery visible.
FORMAT_FAMILY['misc_social_clip'] = 'social'

# 2. Start the merged column as the RULE labels (the trustworthy core)
videos_df['content_type_final'] = videos_df['content_type']

# 3. Overwrite ONLY the previously-unclassified rows with the ML result.
#    Aligns by index — works because `unclassified` kept base_df's index.
videos_df.loc[unclassified.index, 'content_type_final'] = unclassified['final_label']

# 4. Re-map the coarse family on the merged labels
videos_df['format_family'] = videos_df['content_type_final'].map(FORMAT_FAMILY)

# Add the duration minutes column from the unclassified df
videos_df['dur_min'] = unclassified['dur_min']

# 5. Sanity checks
print(videos_df['content_type_final'].value_counts(), "\n")
print("misc_social_clip:", f"{(videos_df.content_type_final=='misc_social_clip').mean():.0%}")
print("unmapped families (must be 0):", videos_df['format_family'].isna().sum())

NameError: name 'unclassified' is not defined

In [30]:
print(videos_df['format_family'].value_counts(), '\n')

format_family
social           1193
match            1138
show              686
media             269
feature           125
signing            63
behind_scenes      57
watch_party        40
Name: count, dtype: int64

In [31]:
videos_df

,video_id,channel_id,title,description,published_at,duration,view_count,like_count,comment_count,fetched_at,cluster,content_type,format_family,content_type_final
0,J8KtvKKDsBI,UCnqj91wjXAT0bsmxF1fHWBA,Inside LAFC | Episode 211 - A Strong Start,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-21T08:27:48Z,PT49M46S,1129,88,4,2026-07-21T18:13:52.868219+00:00,3,inside_lafc,show,inside_lafc
1,6IGiJLX6zIA,UCnqj91wjXAT0bsmxF1fHWBA,Sonny's goal from pitchside 🤳,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-21T05:15:15Z,PT17S,9169,901,20,2026-07-21T18:13:52.868219+00:00,5,goal_clip,match,goal_clip
2,dk5FTY2zHEI,UCnqj91wjXAT0bsmxF1fHWBA,Son Heung-Min | EVERY ANGLE of his derby goal ...,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-20T07:17:45Z,PT2M10S,10782,1373,100,2026-07-21T18:13:52.868219+00:00,5,goal_clip,match,goal_clip
3,WGLkpecuCyA,UCnqj91wjXAT0bsmxF1fHWBA,LAFC Weekly | Episode 15 | 2026,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-19T01:00:21Z,PT21M,2106,167,9,2026-07-21T18:13:52.868219+00:00,0,lafc_weekly,show,lafc_weekly
4,rjdbdSE3TNo,UCnqj91wjXAT0bsmxF1fHWBA,A Night To Remember | LAG vs LAFC,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-18T22:58:28Z,PT25S,2759,457,31,2026-07-21T18:13:52.868219+00:00,0,unclassified,match,match_preview
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3566,8yoRN5MvJP0,UCnqj91wjXAT0bsmxF1fHWBA,Somos LAFC,"Nuestra Ciudad, Nuestro Club, Nuestro Escudo. ...",2016-01-08T00:27:56Z,PT2M,10264,165,16,2026-07-21T18:13:52.868219+00:00,0,unclassified,social,misc_social_clip
3567,Emczin-vSFQ,UCnqj91wjXAT0bsmxF1fHWBA,WE ARE LAFC,"Our City, Our Club, Our Crest. We are LAFC.",2016-01-07T17:51:44Z,PT2M,146275,1160,191,2026-07-21T18:13:52.868219+00:00,0,unclassified,match,highlights
3568,a63ytKgBTAc,UCnqj91wjXAT0bsmxF1fHWBA,John Thorrington announcement on SportsCenter,"Check out SportsCenter, giving some airtime to...",2015-12-09T23:54:13Z,PT27S,2094,24,2,2026-07-21T18:13:52.868219+00:00,0,unclassified,social,misc_social_clip
3569,QJP0ITdmAeo,UCnqj91wjXAT0bsmxF1fHWBA,Building Together: LAFC Stadium Workshop,We asked our supporters to help us design our ...,2015-11-24T19:50:33Z,PT1M1S,6295,73,5,2026-07-21T18:13:52.868219+00:00,0,unclassified,match,match_preview
3570,BPO8RNyuCHs,UCnqj91wjXAT0bsmxF1fHWBA,A Look Back at Year One,Today we proudly mark the one-year anniversary...,2015-10-30T17:09:11Z,PT1M,5611,81,7,2026-07-21T18:13:52.868219+00:00,0,unclassified,social,misc_social_clip

Dropping the columns I don't need and creating a new data frame, so it won't later get confused with the videos sql table.

In [35]:
classified_videos_df = videos_df.drop(['cluster', 'content_type'], axis=1)
classified_videos_df

,video_id,channel_id,title,description,published_at,duration,view_count,like_count,comment_count,fetched_at,format_family,content_type_final
0,J8KtvKKDsBI,UCnqj91wjXAT0bsmxF1fHWBA,Inside LAFC | Episode 211 - A Strong Start,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-21T08:27:48Z,PT49M46S,1129,88,4,2026-07-21T18:13:52.868219+00:00,show,inside_lafc
1,6IGiJLX6zIA,UCnqj91wjXAT0bsmxF1fHWBA,Sonny's goal from pitchside 🤳,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-21T05:15:15Z,PT17S,9169,901,20,2026-07-21T18:13:52.868219+00:00,match,goal_clip
2,dk5FTY2zHEI,UCnqj91wjXAT0bsmxF1fHWBA,Son Heung-Min | EVERY ANGLE of his derby goal ...,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-20T07:17:45Z,PT2M10S,10782,1373,100,2026-07-21T18:13:52.868219+00:00,match,goal_clip
3,WGLkpecuCyA,UCnqj91wjXAT0bsmxF1fHWBA,LAFC Weekly | Episode 15 | 2026,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-19T01:00:21Z,PT21M,2106,167,9,2026-07-21T18:13:52.868219+00:00,show,lafc_weekly
4,rjdbdSE3TNo,UCnqj91wjXAT0bsmxF1fHWBA,A Night To Remember | LAG vs LAFC,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-18T22:58:28Z,PT25S,2759,457,31,2026-07-21T18:13:52.868219+00:00,match,match_preview
...,...,...,...,...,...,...,...,...,...,...,...,...
3566,8yoRN5MvJP0,UCnqj91wjXAT0bsmxF1fHWBA,Somos LAFC,"Nuestra Ciudad, Nuestro Club, Nuestro Escudo. ...",2016-01-08T00:27:56Z,PT2M,10264,165,16,2026-07-21T18:13:52.868219+00:00,social,misc_social_clip
3567,Emczin-vSFQ,UCnqj91wjXAT0bsmxF1fHWBA,WE ARE LAFC,"Our City, Our Club, Our Crest. We are LAFC.",2016-01-07T17:51:44Z,PT2M,146275,1160,191,2026-07-21T18:13:52.868219+00:00,match,highlights
3568,a63ytKgBTAc,UCnqj91wjXAT0bsmxF1fHWBA,John Thorrington announcement on SportsCenter,"Check out SportsCenter, giving some airtime to...",2015-12-09T23:54:13Z,PT27S,2094,24,2,2026-07-21T18:13:52.868219+00:00,social,misc_social_clip
3569,QJP0ITdmAeo,UCnqj91wjXAT0bsmxF1fHWBA,Building Together: LAFC Stadium Workshop,We asked our supporters to help us design our ...,2015-11-24T19:50:33Z,PT1M1S,6295,73,5,2026-07-21T18:13:52.868219+00:00,match,match_preview
3570,BPO8RNyuCHs,UCnqj91wjXAT0bsmxF1fHWBA,A Look Back at Year One,Today we proudly mark the one-year anniversary...,2015-10-30T17:09:11Z,PT1M,5611,81,7,2026-07-21T18:13:52.868219+00:00,social,misc_social_clip

Writing the classfied videos data frame to the sqlite database.

In [36]:
classified_videos_df.to_sql('classified_videos', conn, if_exists='replace', index=False)

3571

Testing if the new table is in the database and it is.

In [38]:
query = '''
SELECT *
FROM classified_videos 
'''
test = pd.read_sql(query, conn)

test

,video_id,channel_id,title,description,published_at,duration,view_count,like_count,comment_count,fetched_at,format_family,content_type_final
0,J8KtvKKDsBI,UCnqj91wjXAT0bsmxF1fHWBA,Inside LAFC | Episode 211 - A Strong Start,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-21T08:27:48Z,PT49M46S,1129,88,4,2026-07-21T18:13:52.868219+00:00,show,inside_lafc
1,6IGiJLX6zIA,UCnqj91wjXAT0bsmxF1fHWBA,Sonny's goal from pitchside 🤳,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-21T05:15:15Z,PT17S,9169,901,20,2026-07-21T18:13:52.868219+00:00,match,goal_clip
2,dk5FTY2zHEI,UCnqj91wjXAT0bsmxF1fHWBA,Son Heung-Min | EVERY ANGLE of his derby goal ...,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-20T07:17:45Z,PT2M10S,10782,1373,100,2026-07-21T18:13:52.868219+00:00,match,goal_clip
3,WGLkpecuCyA,UCnqj91wjXAT0bsmxF1fHWBA,LAFC Weekly | Episode 15 | 2026,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-19T01:00:21Z,PT21M,2106,167,9,2026-07-21T18:13:52.868219+00:00,show,lafc_weekly
4,rjdbdSE3TNo,UCnqj91wjXAT0bsmxF1fHWBA,A Night To Remember | LAG vs LAFC,Watch LAFC on *MLS Season Pass* on the  Apple...,2026-07-18T22:58:28Z,PT25S,2759,457,31,2026-07-21T18:13:52.868219+00:00,match,match_preview
...,...,...,...,...,...,...,...,...,...,...,...,...
3566,8yoRN5MvJP0,UCnqj91wjXAT0bsmxF1fHWBA,Somos LAFC,"Nuestra Ciudad, Nuestro Club, Nuestro Escudo. ...",2016-01-08T00:27:56Z,PT2M,10264,165,16,2026-07-21T18:13:52.868219+00:00,social,misc_social_clip
3567,Emczin-vSFQ,UCnqj91wjXAT0bsmxF1fHWBA,WE ARE LAFC,"Our City, Our Club, Our Crest. We are LAFC.",2016-01-07T17:51:44Z,PT2M,146275,1160,191,2026-07-21T18:13:52.868219+00:00,match,highlights
3568,a63ytKgBTAc,UCnqj91wjXAT0bsmxF1fHWBA,John Thorrington announcement on SportsCenter,"Check out SportsCenter, giving some airtime to...",2015-12-09T23:54:13Z,PT27S,2094,24,2,2026-07-21T18:13:52.868219+00:00,social,misc_social_clip
3569,QJP0ITdmAeo,UCnqj91wjXAT0bsmxF1fHWBA,Building Together: LAFC Stadium Workshop,We asked our supporters to help us design our ...,2015-11-24T19:50:33Z,PT1M1S,6295,73,5,2026-07-21T18:13:52.868219+00:00,match,match_preview
3570,BPO8RNyuCHs,UCnqj91wjXAT0bsmxF1fHWBA,A Look Back at Year One,Today we proudly mark the one-year anniversary...,2015-10-30T17:09:11Z,PT1M,5611,81,7,2026-07-21T18:13:52.868219+00:00,social,misc_social_clip